name: shithappens-dev
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pandas
  - ca-certificates
  - certifi
  - openssl
  - black
  - isort
  - openpyxl
  - build
  - twine
  - pypdf2
  - tqdm
